[package]
name = "zeraus"
version = "0.1.0"
edition = "2021"

[features]
no_std = []
text = []

[dependencies]
fontdue = { version = "0.9.2", optional = true }
nostd = "0.1.3"
tinytga = "0.5.0"
embedded-graphics = "0.8.1"

[dev-dependencies]
png = "0.17.16"
